---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: uptime-db
  namespace: uptime
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBhnVZzgWf+m9MQomRj9Bm/l0F9300ZNjsxTQH+zCec4jGeW6ujCqWxUpnIYAuFhC3In1tIba3Ty00NGfABSudgMxtieyOeB4k2bD9MNFdUF6cMULiVy4fC55RyvKD0AMcFsfIfQL0XL3iSXx9kWjdkLni4ijKicqWHAXWhdgUZD+IQZ7RCW0DtpxNH4XOYQm40GOhU6HJ3f7bT2cQSEv95mp6PmgFqiarV0Zt++r9fvUB/JcHUNM2jVVfby2h3oKEak9EoUA4ruKBn18skjf7mxOY59eVK3brLkhZRZ/9J7ccki3g0rfBjYnnOF8GAIAyDzDhtXVZbeB4tfwENd2e+fuchSNuDK0uVCAmyauao4zVox8Tt5IQkZhPQGVTaAppWMhPO7Y5N+Dw4I/APli4WnD7WNXhCgIKQd83WRqpiLvD8RxnXr2O4o1Wfs8iI7M2g7mwC+p/14jDqvJRg0o5fyG9JsW8OKYj5gt02c01yE1mL4GeWkuW6bY+Z1GZDUuis30O20DxEM1soNRXcv6IJzADsreVSYbPj27icVF5IYA3lLvgh/1+YhZcUEpJbUdF9z7XieFslAFiyqMFsopjaeKaUwNBdk62qRmJXAMKJiOT5/Hd3u0fZHW2sKGrBo2SMEuSrQZxSGwX2U4XoyJAb7QLGRLO85zGs4tw7+QnL5iAi8CTpC531hTqEqrSndc76N3YaZ4XjWSzXQgsEmp9LGQu4d87O+lAcHASlxMJWYmQoUafOG2EH2iaGNBPh0VM=
  template:
    metadata:
      name: uptime-db
      namespace: uptime
